name: ABot API Testing Pipeline

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Install Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Install Newman (Postman CLI)
    - name: Install Newman
      run: npm install -g newman

    # Run the Postman Collection with Newman
    - name: Run Postman Collection
      run: |
        newman run ./postman/ABot_Test_Collection.json \
          --environment ./postman/ABot_Environment.json \
          --global-var "ABOT_USERNAME=${{ secrets.ABOT_USERNAME }}" \
          --global-var "ABOT_PASSWORD=${{ secrets.ABOT_PASSWORD }}" \
          --global-var "ABOT_BASE_URL=${{ secrets.ABOT_BASE_URL }}"
          
    # Optionally, you can save the test results to a file and upload them
    - name: Save and upload test results
      uses: actions/upload-artifact@v2
      with:
        name: postman-test-results
        path: postman/newman/reports
