name: ABot API Testing Pipeline

on:
  workflow_dispatch:

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Newman and CSV converter
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Create reports directory
      run: mkdir -p postman/newman/reports

    - name: Run Postman Collection and export to JSON
      run: |
        newman run ./postman/ABot_Test_Collection.json \
          --reporters cli,json \
          --reporter-json-export postman/newman/reports/results.json

    - name: Convert JSON to CSV (with explanation)
      run: |
        node -e "
        const fs = require('fs');
        const json = JSON.parse(fs.readFileSync('postman/newman/reports/results.json'));
        const statusExplain = {
          200: 'OK - API executed successfully',
          201: 'Created - Resource created successfully',
          401: 'Unauthorized - Login failed or token missing'
        };
        const csv = ['iteration,item.name,response.code,response.status,explanation'];
        json.run.executions.forEach(exec => {
          const code = exec.response.code;
          const status = exec.response.status;
          const explanation = statusExplain[code] || 'Unknown Status';
          csv.push([
            exec.cursor?.iteration || 0,
            exec.item.name,
            code,
            status,
            explanation
          ].join(','));
        });
        fs.writeFileSync('postman/newman/reports/results.csv', csv.join('\n'));
        "

   

    - name: Upload test results (CSV)
      uses: actions/upload-artifact@v4
      with:
        name: postman-test-results
        path: postman/newman/reports/results.csv
