name: Test Baremetal Package Name

on:
  push:
    tags:
      - 'v*'  # e.g. v0.1.3.rc6

jobs:
  test-package-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create dummy directory
        run: |
          mkdir ios-mcn-ran
          echo "This is a test file" > ios-mcn-ran/README.txt

      - name: Package with tag-based name
        run: |
          TAG_NAME=${{ github.ref_name }}
          PACKAGE_NAME="ios-mcn-ran-dist-baremetal-${TAG_NAME}.tar.gz"
          tar -czvf "$PACKAGE_NAME" ios-mcn-ran
          echo "✅ Created package: $PACKAGE_NAME"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-baremetal-package
          path: ios-mcn-ran-dist-baremetal-${{ github.ref_name }}.tar.gz
