name: ABot API Test Execution

on:
  workflow_dispatch:

jobs:
  run-abot-tests:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Newman
      run: npm install -g newman newman-reporter-htmlextra

    - name: Run ABot Postman Collection
      run: |
        mkdir -p postman/newman/reports

        newman run postman/ABot_API.postman_collection.json \
          --environment postman/ABot_Environment.json \
          --reporters cli,json,htmlextra \
          --reporter-json-export postman/newman/reports/results.json \
          --reporter-htmlextra-export postman/newman/reports/results.html

    - name: Upload test report (HTML)
      uses: actions/upload-artifact@v4
      with:
        name: abot-api-results-html
        path: postman/newman/reports/results.html

    - name: Upload test report (JSON)
      uses: actions/upload-artifact@v4
      with:
        name: abot-api-results-json
        path: postman/newman/reports/results.json
