name: Auto Generate Release Notes

on:
  push:
    tags:
      - 'v*'   # Only runs on tags like v1.0.0
  workflow_dispatch:

jobs:
  generate_release_notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate release notes and publish release
        run: |
          gh release create "$GITHUB_REF_NAME" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GHCRUSER }}
